# Generated by Django 3.1.3 on 2020-11-10 17:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique_for_date='start_datetime')),
                ('start_datetime', models.DateTimeField()),
            ],
        ),
    ]
