# Generated by Django 3.1.3 on 2020-11-10 20:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('event', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='events.event')),
            ],
            options={
                'verbose_name_plural': 'Ticket Availabilities',
            },
        ),
        migrations.AddConstraint(
            model_name='ticketavailability',
            constraint=models.UniqueConstraint(fields=('event', 'type'), name='unique_type'),
        ),
    ]
